/****************************************************************************
*   Generated by ACUITY 5.0.0
*   Match ovxlib 1.0.12
*
*   Neural Network global header file
****************************************************************************/
#ifndef _VNN_GLOBAL_H_
#define _VNN_GLOBAL_H_

/*
 * This file will be deprecated in the future
 */

#endif
