/****************************************************************************
*
*    Copyright (c) 2019 Vivante Corporation
*
*    Permission is hereby granted, free of charge, to any person obtaining a
*    copy of this software and associated documentation files (the "Software"),
*    to deal in the Software without restriction, including without limitation
*    the rights to use, copy, modify, merge, publish, distribute, sublicense,
*    and/or sell copies of the Software, and to permit persons to whom the
*    Software is furnished to do so, subject to the following conditions:
*
*    The above copyright notice and this permission notice shall be included in
*    all copies or substantial portions of the Software.
*
*    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
*    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
*    DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/
#ifndef _VSI_NN_OP_LSTMUNIT_ACTIVATION_H
#define _VSI_NN_OP_LSTMUNIT_ACTIVATION_H

#include "vsi_nn_types.h"

/* c -> cifg, l -> layer norm, p -> projection, h -> peephole, b -> hybrid bias fp32, s -> standard*/

enum {
    ACT_INPUT_FC_I, //optional
    ACT_INPUT_FC_F,
    ACT_INPUT_FC_C,
    ACT_INPUT_FC_O,
    ACT_CSTATE_IN,
    ACT_HSTATE_FC_I, //optional
    ACT_HSTATE_FC_F, //optional
    ACT_HSTATE_FC_C, //optional
    ACT_HSTATE_FC_O, //optional
    ACT_DATA_B,      //optional
    ACT_LN_W,        //optional

    ACT_INPUTS_COUNT,

    ACT_OUTPUT = 0,
    ACT_CSTATE_OUT,
    ACT_HSTATE_OUT, //optional

    ACT_OUTUTS_COUNT,

    ACT_PARAM_COUT = ACT_INPUTS_COUNT + ACT_OUTUTS_COUNT,
};

enum {
    LSTMUNIT_ACT_CPU_KERNEL,

    LSTMUNIT_ACT_CLP_F16TOF16_F32_KERNEL,
    LSTMUNIT_ACT_CLP_F16TOF16_F16_KERNEL,
    LSTMUNIT_ACT_LP_F16TOF16_F32_KERNEL,
    LSTMUNIT_ACT_LP_F16TOF16_F16_KERNEL,
    LSTMUNIT_ACT_CL_F16TOF16_F16_KERNEL,
    LSTMUNIT_ACT_CL_F16TOI16_F16_KERNEL,
    LSTMUNIT_ACT_CL_F16TOI8_F16_KERNEL,
    LSTMUNIT_ACT_CL_F16TOU8_F16_KERNEL,
    LSTMUNIT_ACT_CL_F16TOF16_F32_KERNEL,
    LSTMUNIT_ACT_CL_F16TOI16_F32_KERNEL,
    LSTMUNIT_ACT_CL_F16TOI8_F32_KERNEL,
    LSTMUNIT_ACT_CL_F16TOU8_F32_KERNEL,
    LSTMUNIT_ACT_L_F16TOF16_F16_KERNEL,
    LSTMUNIT_ACT_L_F16TOI16_F16_KERNEL,
    LSTMUNIT_ACT_L_F16TOI8_F16_KERNEL,
    LSTMUNIT_ACT_L_F16TOU8_F16_KERNEL,
    LSTMUNIT_ACT_L_F16TOF16_F32_KERNEL,
    LSTMUNIT_ACT_L_F16TOI16_F32_KERNEL,
    LSTMUNIT_ACT_L_F16TOI8_F32_KERNEL,
    LSTMUNIT_ACT_L_F16TOU8_F32_KERNEL,

    LSTMUNIT_ACT_LN_KERNEL_COUNTS,

    LSTMUNIT_ACT_BP_F16TOF16_F32_KERNEL = 0,
    LSTMUNIT_ACT_BP_F16TOF16_F16_KERNEL,
    LSTMUNIT_ACT_B_F16TOF16_F16_KERNEL,
    LSTMUNIT_ACT_B_F16TOI16_F16_KERNEL,
    LSTMUNIT_ACT_B_F16TOI8_F16_KERNEL,
    LSTMUNIT_ACT_B_F16TOU8_F16_KERNEL,
    LSTMUNIT_ACT_B_F16TOF16_F32_KERNEL,
    LSTMUNIT_ACT_B_F16TOI16_F32_KERNEL,
    LSTMUNIT_ACT_B_F16TOI8_F32_KERNEL,
    LSTMUNIT_ACT_B_F16TOU8_F32_KERNEL,
    LSTMUNIT_ACT_CBP_F16TOF16_F32_KERNEL,
    LSTMUNIT_ACT_CBP_F16TOF16_F16_KERNEL,
    LSTMUNIT_ACT_CB_F16TOF16_F16_KERNEL,
    LSTMUNIT_ACT_CB_F16TOI16_F16_KERNEL,
    LSTMUNIT_ACT_CB_F16TOI8_F16_KERNEL,
    LSTMUNIT_ACT_CB_F16TOU8_F16_KERNEL,
    LSTMUNIT_ACT_CB_F16TOF16_F32_KERNEL,
    LSTMUNIT_ACT_CB_F16TOI16_F32_KERNEL,
    LSTMUNIT_ACT_CB_F16TOI8_F32_KERNEL,
    LSTMUNIT_ACT_CB_F16TOU8_F32_KERNEL,

    LSTMUNIT_ACT_HYBRID_KERNEL_FP16_COUNTS,

    LSTMUNIT_ACT_BP_U8TOF16_F32_KERNEL = 0,
    LSTMUNIT_ACT_BP_U8TOF16_F16_KERNEL,
    LSTMUNIT_ACT_B_U8TOF16_F16_KERNEL,
    LSTMUNIT_ACT_B_U8TOU8_F16_KERNEL,
    LSTMUNIT_ACT_B_U8TOF16_F32_KERNEL,
    LSTMUNIT_ACT_B_U8TOU8_F32_KERNEL,
    LSTMUNIT_ACT_CBP_U8TOF16_F32_KERNEL,
    LSTMUNIT_ACT_CBP_U8TOF16_F16_KERNEL,
    LSTMUNIT_ACT_CB_U8TOF16_F16_KERNEL,
    LSTMUNIT_ACT_CB_U8TOU8_F16_KERNEL,
    LSTMUNIT_ACT_CB_U8TOF16_F32_KERNEL,
    LSTMUNIT_ACT_CB_U8TOU8_F32_KERNEL,

    LSTMUNIT_ACT_HYBRID_KERNEL_U8_COUNTS,

    LSTMUNIT_ACT_HYBRID_KERNEL_COUNTS = LSTMUNIT_ACT_HYBRID_KERNEL_FP16_COUNTS + LSTMUNIT_ACT_HYBRID_KERNEL_U8_COUNTS,

    LSTMUNIT_ACT_SP_F16TOF16_F32_KERNEL = 0,
    LSTMUNIT_ACT_SP_F16TOF16_F16_KERNEL,
    LSTMUNIT_ACT_S_F16TOF16_F16_KERNEL,
    LSTMUNIT_ACT_S_F16TOI16_F16_KERNEL,
    LSTMUNIT_ACT_S_F16TOI8_F16_KERNEL,
    LSTMUNIT_ACT_S_F16TOU8_F16_KERNEL,
    LSTMUNIT_ACT_S_F16TOF16_F32_KERNEL,
    LSTMUNIT_ACT_S_F16TOI16_F32_KERNEL,
    LSTMUNIT_ACT_S_F16TOI8_F32_KERNEL,
    LSTMUNIT_ACT_S_F16TOU8_F32_KERNEL,
    LSTMUNIT_ACT_CSP_F16TOF16_F32_KERNEL,
    LSTMUNIT_ACT_CSP_F16TOF16_F16_KERNEL,
    LSTMUNIT_ACT_CS_F16TOF16_F16_KERNEL,
    LSTMUNIT_ACT_CS_F16TOI16_F16_KERNEL,
    LSTMUNIT_ACT_CS_F16TOI8_F16_KERNEL,
    LSTMUNIT_ACT_CS_F16TOU8_F16_KERNEL,
    LSTMUNIT_ACT_CS_F16TOF16_F32_KERNEL,
    LSTMUNIT_ACT_CS_F16TOI16_F32_KERNEL,
    LSTMUNIT_ACT_CS_F16TOI8_F32_KERNEL,
    LSTMUNIT_ACT_CS_F16TOU8_F32_KERNEL,

    LSTMUNIT_ACT_ST_KERNEL_FP16_COUNTS,

    LSTMUNIT_ACT_SP_U8TOF16_F32_KERNEL = 0,
    LSTMUNIT_ACT_SP_U8TOF16_F16_KERNEL,
    LSTMUNIT_ACT_S_U8TOF16_F16_KERNEL,
    LSTMUNIT_ACT_S_U8TOU8_F16_KERNEL,
    LSTMUNIT_ACT_S_U8TOF16_F32_KERNEL,
    LSTMUNIT_ACT_S_U8TOU8_F32_KERNEL,
    LSTMUNIT_ACT_CSP_U8TOF16_F32_KERNEL,
    LSTMUNIT_ACT_CSP_U8TOF16_F16_KERNEL,
    LSTMUNIT_ACT_CS_U8TOF16_F16_KERNEL,
    LSTMUNIT_ACT_CS_U8TOU8_F16_KERNEL,
    LSTMUNIT_ACT_CS_U8TOF16_F32_KERNEL,
    LSTMUNIT_ACT_CS_U8TOU8_F32_KERNEL,

    LSTMUNIT_ACT_ST_KERNEL_U8_COUNTS,
    LSTMUNIT_ACT_ST_KERNEL_COUNTS = LSTMUNIT_ACT_ST_KERNEL_FP16_COUNTS + LSTMUNIT_ACT_ST_KERNEL_U8_COUNTS,

    LSTMUNIT_ACT_KERNELS_COUNT = LSTMUNIT_ACT_LN_KERNEL_COUNTS + LSTMUNIT_ACT_HYBRID_KERNEL_COUNTS
    + LSTMUNIT_ACT_ST_KERNEL_COUNTS,
};

typedef struct _vsi_nn_lstmunit_activation_param
    {
    float cell_clip;
    float proj_clip;
    float forget_bias;
    uint8_t is_cifg;
    uint8_t is_projection;
    uint8_t is_layer_norm;
    uint8_t is_peephole; /* not supported now*/
    uint8_t is_hybrid; /*hybrid mode and bias format is fp32 */
    } vsi_nn_lstmunit_activation_param;

#endif

